import { Component, OnInit } from '@angular/core';
import {BfGrowlService} from '../../../../bf-ui-lib/src/lib/bf-growl/bf-growl.service';
import {IbfInputCtrl} from '../../../../bf-ui-lib/src/lib/bf-input/bf-input.component';

@Component({
  selector: 'app-bf-textarea-demo',
  templateUrl: './bf-textarea-demo.component.html',
  styleUrls: ['./bf-textarea-demo.component.scss']
})
export class BfTextareaDemoComponent implements OnInit {
  public name = BfTextareaDoc.name;
  public desc = BfTextareaDoc.desc;
  public api = BfTextareaDoc.api;
  public instance = BfTextareaDoc.instance;
  public instance2 = `<bf-textarea</bf-textarea>`;
  public myVal = '';
  public flatExample = '<bf-textarea class="flat" [ngModel]="myVal"></bf-textarea>';
  public resizeExample = '<bf-textarea class="resize" [ngModel]="myVal"></bf-textarea>';
  public inputRef: IbfInputCtrl; // bf-textarea controller object (ctrlObject)
  public cssReset = `$textarea-optional-color  : $optional-color !default;  // <-- this is a bootstrap default
$textarea-focused-color   : $focused-color !default;
$textarea-disabled-color  : $disabled-color !default;
$textarea-required-color  : $required-color !default;
$textarea-invalid-color   : $invalid-color !default;`;

  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n             `;
  public code = ``;
  public conf = {
    isRequired: false,
    isDisabled: false,
    rows: 4,
    hasErrOnPristine: false,
    isMinLen: false, minLen: 1,
    isMaxLen: false, maxLen: 1,
    hasLabel: true,      labelText: 'view.common.username',
    hasPlaceholder: false, placeholder: 'view.common.placeholder',
    hasTooltip: false, tooltipText: 'view.tooltip.message', tooltipPos: null, tooltipBody: false,
    hasPattern: false, pattern: '[A-Za-z]{3,20}',
    hasValidIf: false, hasBfValidator: false,
    hasManualErr: false,
    autofocus: false,

    hasKeyDown: false, hasKeyEsc: false, hasKeyCtrlEnter: false,
    hasOnLoad: false, hasBeforeChange: false,
    hasFlat: false,
  };
  public upComp = () => {
    this.code = `<bf-textarea `;

    let compClasses = '';
    if (this.conf.hasFlat) { compClasses += (!!compClasses.length ? ' ' : '') + 'flat'; }
    if (!!compClasses) {
      this.code += `class="${compClasses}"` + this.bsStr;
    }
    this.code += `[(ngModel)]="myVal"`;

    if (this.conf.hasLabel)       { this.code += this.bsStr + `bfLabel="${this.conf.labelText}"`; }
    if (this.conf.hasPlaceholder) { this.code += this.bsStr + `bfPlaceholder="${this.conf.placeholder}"`; }
    if (this.conf.rows !== 4) { this.code += this.bsStr + `[bfRows]="${this.conf.rows}"`; }
    if (this.conf.isRequired) { this.code += this.bsStr + `[bfRequired]="true"`; }
    if (this.conf.isDisabled) { this.code += this.bsStr + `[bfDisabled]="true"`; }
    if (this.conf.hasErrOnPristine)  { this.code += this.bsStr + `[bfErrorOnPristine]="true"`; }
    if (this.conf.autofocus) { this.code += this.bsStr + `[bfAutoFocus]="true"`; }

    if (this.conf.isMinLen)    { this.code += this.bsStr + `bfMinlength="${this.conf.minLen}"`; }
    if (this.conf.isMaxLen)    { this.code += this.bsStr + `bfMaxlength="${this.conf.maxLen}"`; }
    if (this.conf.hasPattern)  { this.code += this.bsStr + `bfPattern="${this.conf.pattern}"`; }
    if (this.conf.hasValidIf)  { this.code += this.bsStr + `[bfValidIf]="val1 === 'AAA'"`; }
    if (this.conf.hasBfValidator) { this.code += this.bsStr + `[bfValidator]="bfValidatorFn"`; }

    if (this.conf.hasTooltip) {
      this.code += this.bsStr + `bfTooltip="${this.conf.tooltipText}"`;
      if (!!this.conf.tooltipPos)  { this.code += this.bsStr + `bfTooltipPos="${this.conf.tooltipPos}"`; }
      if (!!this.conf.tooltipBody) { this.code += this.bsStr + `bfTooltipBody="${this.conf.tooltipBody}"`; }
    }

    if (this.conf.hasKeyDown) { this.code += this.bsStr + `(bfOnKeyDown)="onClickFn($event)"`; }
    if (this.conf.hasKeyEsc)  { this.code += this.bsStr + `(bfOnEsc)="onClickFn($event)"`; }
    if (this.conf.hasKeyCtrlEnter) { this.code += this.bsStr + `(bfOnSave)="onClickFn($event)"`; }

    if (this.conf.hasBeforeChange) { this.code += this.bsStr + `(bfBeforeChange)="doSomething($event)"`; }
    if (this.conf.hasOnLoad || this.conf.hasManualErr) { this.code += this.bsStr + `(bfOnLoaded)="ctrl = $event"`; }

    this.code += (`>` + this.brStr + `</bf-textarea>`);

    if (this.conf.hasBfValidator) {
      this.code += `\n \n bfValidatorFn = (value, ctrl) => value === 'BBB' ? null : { label : 'wrooong' };`;
    }
    if (this.conf.hasManualErr) {
      this.code += `\n \n public ctrl: IbfInputCtrl; // bfTextarea controller object\n`;
      this.code += ` ctrl.addError({ label: 'manual error here' });\n`;
      this.code += ` ctrl.removeError();\n`;
    }
  };



  constructor(
    public growl: BfGrowlService,
  ) { }

  ngOnInit() { }


  public bfValidatorFn = (value, ctrl) => {
    return (value === 'BBB') ? null : { label : 'wrooong' };
  };

}


export const BfTextareaDoc = {
  name    : `bf-textarea`,
  uiType  : 'component',
  desc    : `Generates a textarea component.`,
  api     : `[(ngModel)]     : The ngModel directive is linked to the inner <textarea>, so that can be used as a form element with ngForm (status is propagated).
[bfRows]        : Number of rows of the <textarea> (4 by default).
[bfLabel]       : Label of the input (automatically translated). If not provided, no label is displayed.
[bfRequired]    : Whether the input is required or not
[bfDisabled]    : Whether the input is disabled or not
[bfPlaceholder] : Placeholder text (automatically translated)
[bfAutoFocus]   : (true/false) If true, the textarea will get focused automatically once is initialized (linked to the view)

[bfErrorText]   : Custom error text (label) to display when invalid value
[bfErrorPos]    : Custom position where to display the error text. Values = ['top-right', 'bottom-left', 'bottom-right', 'none', 'default'].
[bfErrorOnPristine] : If true, errors will be shown in pristine state too (by default pristine shows as valid always).
[bfMinlength]   : Min number of chars. Built in validator "minlength"
[bfMaxlength]   : Max number of chars. Built in validator "maxlength". Null means no max. It blocks input if limit.
[bfPattern]     : Regex validator. Built in validator "pattern". Null means no validation.
[bfValidIf]     : Boolean expression to determine the input validity
[bfValidator]   : Callback function called every time the internal ngModel validates its value. Parameter = current value of the model.
                  It should return null (valid) or error object (invalid).

[bfTooltip]     : If label provided, adds a info badge with a tooltip (automatically translated)
[bfTooltipPos]  : Position of the tooltip (top by default)
[bfTooltipBody] : Whether the tooltip is append to the body (default true) or next the the html element (false). The parent contaniner may affect the visibility of the tooltip

(bfOnLoaded)    : Emitter to catch the moment when the component is ready (ngAfterViewInit)
(bfBeforeChange): Emitter to catch the next value before it is set. It returns both (currentValue, nextValue)
(bfOnKeyDown)   : Triggered when a key is pressed on the textarea
(bfOnEsc)       : Triggered when keys Esc is pressed.
(bfOnSave)      : Triggered when keys Ctrl + Enter are pressed. This represents the keyboard combination to save the value
`,
  instance: `<bf-textarea [(ngModel)]="myVal" bfLabel="My Text"></bf-textarea>`,
  demoComp: BfTextareaDemoComponent
};
