// bf-status-badge = 'bf-btn'
// BfStatusBadge = 'BfBtn'


import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-bf-status-badge-demo',
  templateUrl: './bf-status-badge-demo.component.html',
  styleUrls: ['./bf-status-badge-demo.component.scss']
})
export class BfStatusBadgeDemoComponent implements OnInit {
  public name = BfStatusBadgeDoc.name;
  public desc = BfStatusBadgeDoc.desc;
  public api = BfStatusBadgeDoc.api;
  public instance = BfStatusBadgeDoc.instance;

  public instance2 = `<bf-status-badge [bfStatus]="item.status"
                 [bfLabel]="item.label">
</bf-status-badge>`;
  public instance3 = `<bf-status-badge [bfStatus]="item.status = true"
                 [bfLabel]="['yes','no']">
</bf-status-badge>
<bf-status-badge [bfStatus]="item.status = false"
                 [bfLabel]="['yes','no']">
</bf-status-badge>`;
  public instance4 = `<bf-status-badge [bfStatus]="item.status = 2"
                 bfLabel="Circle Example"
                 [bfCircle]="true">
</bf-status-badge>`;
  public instance5 = `<bf-status-badge [bfStatus]="item.status" [bfColor]="'7f3fc0'">
</bf-status-badge>`;

  public cssReset = `$bf-status-badge-text-color : $white !default;
$bf-status-badge-border     : #f8f8f8 !default;
$bf-status-font-size        : 12px !default;
$bf-status-font-weight      : 600 !default;

$bf-status-active   : $primary_color !default;
$bf-status-inactive : $warning_color !default;
$bf-status-pending  : $quaternary_color !default;
$bf-status-other    : $secondary_color !default;
$bf-status-other2   : $extra_color !default;
$bf-status-other3   : darken($secondary_color, 15) !default;
$bf-status-other4   : darken($bf_color3_shadow2, 20%) !default;
$bf-status-submitted: darken($tertiary_color, 15) !default;`;





  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n                 `;
  public customCompCode = `<bf-dropdown [(ngModel)]="selObj" [bfList]="myList"></bf-dropdown>`;
  public customModCode   = `<bf-status-badge [bfStatus]="0" [bfLabel]="Module default"></bf-status-badge>`;
  public compConf: any = {
    status: 0,
    hasLabel: false,
    isSingleLabel: true,
    labelText: 'My label',
    isCircle: false,
    hasColor: false,
    colorCode: '',
    rows: null,
    hasTooltip: false, tooltipText: 'Hello World', tooltipPos: null, tooltipBody: false
  };
  public modConf: any = {
    status: 0,
    labelText: 'Module default',
    defaultList: [
      { id: 0, name: 'Not Paid' },
      { id: 1, name: 'Partially' },
      { id: 2, name: 'Paid' },
      { id: 3, name: 'Cancelled' },
      { id: 4, name: 'Waiting' },
      { id: 5, name: 'Refunded' },
      { id: 6, name: 'Submitted'}
    ],
    orderColorSet: {
      0: 'bf-color-third',
      1: 'bf-color-fourth',
      2: 'bf-color-first',
      3: 'bf-color-second',
      4: 'bf-color-fifth',
      5: 'bf-color-sixth',
      6: 'bf-color-eighth'
    }
  };
  public statusList = [
    { id: 0, name: 'Active' },
    { id: 1, name: 'Inactive' },
    { id: 2, name: 'Pending' },
    { id: 3, name: 'Other 1' },
    { id: 4, name: 'Other 2' },
    { id: 5, name: 'Other 3' },
    { id: 6, name: 'Other 4' }
  ];

  public setList = () => {
    if (this.compConf.isSingleLabel) {
      this.compConf.labelText = 'My label';
      this.statusList = [
        { id: 0, name: 'Active' },
        { id: 1, name: 'Inactive' },
        { id: 2, name: 'Pending' },
        { id: 3, name: 'Other 1' },
        { id: 4, name: 'Other 2' },
        { id: 5, name: 'Other 3' },
        { id: 6, name: 'Other 4' }
      ];
    } else {
      this.compConf.status = 0;
      this.compConf.labelText = ['None', 'Low', 'Medium', 'High', 'Max'];
      this.statusList = [
        { id: 0, name: 'None' },
        { id: 1, name: 'Low' },
        { id: 2, name: 'Medium' },
        { id: 3, name: 'High' },
        { id: 4, name: 'Max' }
        ];
    }
  }

  public setColor = () => {
    if (this.compConf.hasColor) {
      this.compConf.colorCode = '#00B6F1';
    } else {
      this.compConf.colorCode = '';
    }
  }

  public upComp = () => {
    this.customCompCode = `<bf-status-badge `;


    this.customCompCode += `[bfStatus]="${this.compConf.status}"`;

    if (this.compConf.hasLabel)   { this.customCompCode += this.bsStr + `[bfLabel]="${this.compConf.labelText}"`; }
    if (this.compConf.hasColor)   { this.customCompCode += this.bsStr + `[bfColor]="${this.compConf.colorCode}"`; }
    if (this.compConf.isCircle)   { this.customCompCode += this.bsStr + `[bfCircle]="true"`; }

    if (this.compConf.hasTooltip) {
      this.customCompCode += this.bsStr + `bfTooltip="${this.compConf.tooltipText}"`;
      if (!!this.compConf.tooltipPos)  { this.customCompCode += this.bsStr + `bfTooltipPos="${this.compConf.tooltipPos}"`; }
      if (!!this.compConf.tooltipBody) { this.customCompCode += this.bsStr + `bfTooltipBody="${this.compConf.tooltipBody}"`; }
    }

    this.customCompCode += (`>` + this.brStr + `</bf-status-badge>`);
  }

  public upMod = () => {
    this.customModCode = `<bf-status-badge `;
    this.customModCode += `[bfStatus]="${this.modConf.status}"`;
    this.customModCode += this.bsStr + `[bfLabel]="${this.modConf.labelText}"`;
    this.customModCode += this.bsStr + `[bfColorSet]="modConf.orderColorSet"`;
    this.customModCode += (`>` + this.brStr + `</bf-status-badge>`);
  }

  public updateModStatus = () => {
    this.modConf.labelText = this.modConf.defaultList[this.modConf.status].name;
  }

  constructor() { }

  ngOnInit() { }

}


export const BfStatusBadgeDoc = {
  name    : `bf-status-badge`,
  uiType  : 'component',
  desc    : `Generate a status badge`,
  api     : `[bfStatus]  : Button text
[bfLabel]   : (String) Display the label translated on the status, (Array) list of labels
[bfColor]   : Background Color of the staus
[bfCircle]  : Condition that display the badge in a circle
[bfColorSet]: (ColorSet) array the color set of the status`,
  instance: `<bf-status-badge [bfStatus]="myStatus=0">
</bf-status-badge>
<bf-status-badge [bfStatus]="myStatus=1">
</bf-status-badge>
<bf-status-badge [bfStatus]="myStatus=2">
</bf-status-badge>`,
  demoComp: BfStatusBadgeDemoComponent
};
