import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-bf-no-data-demo',
  templateUrl: './bf-no-data-demo.component.html',
  styleUrls: ['./bf-no-data-demo.component.scss']
})
export class BfNoDataDemoComponent implements OnInit {
  public name = BfNoDataDoc.name;
  public desc = BfNoDataDoc.desc;
  public api = BfNoDataDoc.api;
  public instance = BfNoDataDoc.instance;

  public instance2 =
`<bf-no-data</bf-no-data>`;


  public cssReset = `$no-data-bg: darken($primary_color, 20%) !default;
$no-data-color: $white !default;`;


  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n             `;
  public customCompCode = `<bf-dropdown [(ngModel)]="selObj" [bfList]="myList"></bf-dropdown>`;
  public compConf: any = {
    isRequired: false,
    isDisabled: false,
    rows: null,
    hasLabel: false,   labelText: 'My Description',
    hasTooltip: false, tooltipText: 'Hello World', tooltipPos: null, tooltipBody: false,
  };
  public upComp = () => {
    this.customCompCode = `<bf-no-data `;

    let compClasses = '';
    if (this.compConf.hasFullWidth) { compClasses += (!!compClasses.length ? ' ' : '') + 'full-width'; }
    if (this.compConf.hasSquash)    { compClasses += (!!compClasses.length ? ' ' : '') + 'squash'; }
    if (!!compClasses) {
      this.customCompCode += `class="${compClasses}"` + this.bsStr;
    }
    this.customCompCode += `[(ngModel)]="myVal"` + this.bsStr;
    this.customCompCode += `(ngModelChange)="doSomething($event)"`;

    if (this.compConf.hasLabel)   { this.customCompCode += this.bsStr + `bfLabel="${this.compConf.labelText}"`; }
    if (this.compConf.isRequired) { this.customCompCode += this.bsStr + `[bfRequired]="true"`; }
    if (this.compConf.isDisabled) { this.customCompCode += this.bsStr + `[bfDisabled]="true"`; }

    if (this.compConf.hasTooltip) {
      this.customCompCode += this.bsStr + `bfTooltip="${this.compConf.tooltipText}"`;
      if (!!this.compConf.tooltipPos)  { this.customCompCode += this.bsStr + `bfTooltipPos="${this.compConf.tooltipPos}"`; }
      if (!!this.compConf.tooltipBody) { this.customCompCode += this.bsStr + `bfTooltipBody="${this.compConf.tooltipBody}"`; }
    }

    this.customCompCode += (`>` + this.brStr + `</bf-no-data>`);
  }





  constructor() { }

  ngOnInit() { }

}


export const BfNoDataDoc = {
  name    : `bf-no-data`,
  uiType  : 'component',
  desc    : `Generates an alert with the no data placeholder`,
  api     : `[bfMessage]: The message to display (by default = 'view.common.no_data_to_show')`,
  instance: `<bf-no-data></bf-no-data>`,
  demoComp: BfNoDataDemoComponent
};
