import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-bf-dual-checkbox-demo',
  templateUrl: './bf-dual-checkbox-demo.component.html',
  styleUrls: ['./bf-dual-checkbox-demo.component.scss']
})

export class BfDualCheckboxDemoComponent implements OnInit {
  public name = BfDualCheckboxDoc.name;
  public desc = BfDualCheckboxDoc.desc;
  public api = BfDualCheckboxDoc.api;
  public instance = BfDualCheckboxDoc.instance;
  public value;
  public printValue;
  public label = 'view.common.active';
  public defaultValue;

  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n             `;
  public customCompCode = ``;
  public compConf = {
    bfLabel: 'view.common.active',
    ngModel: 'value',
    isDisabled: false,
    isClassBlock: false,
  };

  public dualCheckboxHtmlStructure = `<div class="dual-checkbox">
  <label>{{bfLabelText$ | async}}</label>
  <div>
    <bf-checkbox
      [class.block]="className"
      bfLabel="view.common.yes"
      [(ngModel)]="checkboxes.yes"
      (ngModelChange)="onChange('yes')"
      [bfDisabled]="bfDisabled"
    ></bf-checkbox>
    <bf-checkbox
      [class.block]="className"
      bfLabel="view.common.no"
      [(ngModel)]="checkboxes.no"
      (ngModelChange)="onChange('no')"
      [bfDisabled]="bfDisabled"
    ></bf-checkbox>
  </div>
</div>`;

  public checkboxHtmlStructure = `<div class="checkbox">
  <label>
    <input type="checkbox" [disabled]="bfDisabled"
           [ngModel]="ngModel" (ngModelChange)="onChange($event)">
    <span class="check-box icon-checkmark3"></span>
    <span class="check-text" [class.has-text]="!!bfLabel">{{bfLabel}}</span>
  </label>
</div>`;

  public upComp = () => {
    this.customCompCode = `<bf-dual-checkbox `;

    let compClasses = '';
    if (this.compConf.isClassBlock) { compClasses += (!!compClasses.length ? ' ' : '') + 'block'; }
    if (!!compClasses) { this.customCompCode += `[className]="${compClasses}"` + this.bsStr; }

    if (this.compConf.bfLabel) { this.customCompCode += `[bfLabel]="${this.compConf.bfLabel}"`; }

    if (this.compConf.ngModel) { this.customCompCode += this.bsStr + `[(ngModel)]="${this.compConf.ngModel}"`; }

    if (this.compConf.isDisabled) { this.customCompCode += this.bsStr + `[isDisabled]="true"`; }

    this.customCompCode += (`>` + this.brStr + `</bf-dual-checkbox>`);
  };

  public returnedValues = () => {
    return this.printValue = this.value === undefined ? 'undefined' : this.value;
  };

  ngOnInit() { }
}
export const BfDualCheckboxDoc = {
  name    : `bf-dual-checkbox`,
  uiType  : 'component',
  desc    : `Implements bf-checkbox to generate a dual boolean checkbox.`,
  api     : `
[(ngModel)]     : The ngModel directive is linked to the bf-checkbox boolean value.
[bfLabel]       : Text of the label (optional)
[bfDisabled]    : Boolean value to disable (true) the input
[className]     : Boolean value to display (true) checkboxes as block elements`,
  instance: `<bf-dual-checkbox [(ngModel)]="defaultValue" bfLabel="Check me"></bf-dual-checkbox>`,
  demoComp: BfDualCheckboxDemoComponent
};
