import { Component, OnInit } from '@angular/core';
import { BfArray } from 'projects/bf-ui-lib/src/lib/bf-prototypes/bf-prototypes';
import { BfPrototypes } from 'projects/bf-ui-lib/src/lib/bf-prototypes/bf-prototypes';

BfPrototypes.run();

// BfPrototypes.run(['Array.getById']);
// BfPrototypes.run(['Array.getByProp']);
// const list1 = [{id:'1'}, {id:'2'}, {id:'3'}, {id:'4'}];
// console.log(BfArray.getByProp.call(list1, 'id', '3'));
// const list = [{id:'1'}, {id:'2'}, {id:'3'}, {id:'4'}, [1,3,5, [9, 1, 2]]];
// console.log('RES', list.getById('33'));
// console.log('RES', list.getByProp('id', '3'));
// console.log('RES', list.getIndexById('3'));
// console.log('RES', list.removeById('23'), list);
// const list2 = list.dCopy();
// list[4][0] = '99999';
// list[4][3][1] = '99999';
// console.log(list, list2);
// console.log('LAST', list.getLast());
//
// const myObj2 = { id: 2, name: 'Max', age: 12 };
// const myObj1 = { id: 1, name: 'Sam', age: 10, isValid: true, dad: myObj2, list };
// console.log(myObj1.keyMap('id, name'));
// console.log(myObj1.keyMap('id, age, isValid'));
//
// const myObj3 = myObj1.dCopy();
// myObj1.name = 'Tom';
// myObj1.dad.name = 'Lu';
// myObj1.list[1].id = 'changed';
// myObj1.list[2] = { id : '99999' };
// console.log(myObj1, myObj3);
// const myVal = 43;
// console.log(myVal.isIn([1,2,3,4,5,6]));
// const val = 'one2';
// console.log(val.isIn(['one','two','three','four']));
//
// let myDate = new Date();
// console.log('MyDate', myDate);
// console.log('to UTC', myDate.toUTC());
// console.log('Trunc min', myDate.truncMin());
// console.log('Trunc h', myDate.truncHour());
// console.log('Trunc d', myDate.truncDay());
// console.log('+ 20 sec', myDate.addSeconds(20));
// console.log('+ 21 min', myDate.addMinutes(21));
// console.log('+ 3 hour', myDate.addHours(3));
// console.log('+ 2 days', myDate.addDays(2));
// console.log('+ 3 months', myDate.addMonths(3));
// console.log('+ 4 years', myDate.addYears(-1).addDays(1));
// let val2 = '32';
// console.log(val2.pad(5));
// console.log(val2.pad(val2.length, '*', 10));
//
// let myObj = { name: 'Tom', age: 20, pass: '3' };
// console.log(myObj);
// myObj.cloneProp('ini', { ini: false });
// console.log(myObj);
// myObj.cloneProp('age', { age: 30 });
// console.log(myObj);
// myObj.cloneProp('pass', { age: 30 });
// console.log(myObj);
// const a = new Date();
// console.log(a);
// a.convertTZ('America/New_York'); console.log(a);
// a.convertTZ('Europe/Dublin'); console.log(a);
// console.log(new Date().convertTZ('Europe/Berlin'));
//
// const list5 = [{id:1, name:'foo'}, {id:2, name:'liz'}, {id:3, name:'tom'}, {id:4, name:'zul'}];
// console.log(list5.getKeyById('name', 3));
// console.log(list5.getKeyByProp('id', 'name', 'zul'));


@Component({
  selector: 'app-bf-prototypes-demo',
  templateUrl: './bf-prototypes-demo.component.html',
  styleUrls: ['./bf-prototypes-demo.component.scss']
})
export class BfPrototypesDemoComponent implements OnInit {
  public name = BfPrototypesDoc.name;
  public desc = BfPrototypesDoc.desc;
  public api = BfPrototypesDoc.api;
  public instance = BfPrototypesDoc.instance;

  public instance2 =
`<bf-prototypes</bf-prototypes>`;


  public cssReset = `$input-border: #ccc !default;
$optional_input_color : $input-border;
$disabled_input_color : #797979;
$primary_color        : #00B6F1;
$warning_color        : #ED0677;
$invalid_input_color  : $warning_color;

.bf-prototypes-form-group {
  ...
}`;


  public example1 = `  import { BfPrototypes } from 'bf-ui-lib';
  BfPrototypes.run();

  const myArray = [{ id: '1' }, { id: '2' }, { id: '3' }];
  const item = myArray.getById('3');`;


  public example2 = `  import { BfArray } from 'bf-ui-lib';

  const myArray = [{ id: '1' }, { id: '2' }, { id: '3' }];
  const item = BfArray.getById.call(myArray, '3');`;

  public arrayT = `Array<T>`;
  public partialT = `Partial<T>`;
  public example3 = `import { BfPrototypes } from 'bf-ui-lib';

BfPrototypes.run(); // This will override all prototypes`;

  public example4 = `// This will define prototypes for only 3 functions
BfPrototypes.run(['Array.getById', 'Array.getByProp', 'Object.dCopy']);`;



  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n             `;
  public customCompCode = `<bf-dropdown [(ngModel)]="selObj" [bfList]="myList"></bf-dropdown>`;
  public compConf: any = {
    isRequired: false,
    isDisabled: false,
    rows: null,
    hasLabel: false,   labelText: 'My Description',
    hasTooltip: false, tooltipText: 'Hello World', tooltipPos: null, tooltipBody: false,
  };
  public upComp = () => {
    this.customCompCode = `<bf-textarea `;

    let compClasses = '';
    if (this.compConf.hasFullWidth) { compClasses += (!!compClasses.length ? ' ' : '') + 'full-width'; }
    if (this.compConf.hasSquash)    { compClasses += (!!compClasses.length ? ' ' : '') + 'squash'; }
    if (!!compClasses) {
      this.customCompCode += `class="${compClasses}"` + this.bsStr;
    }
    this.customCompCode += `[(ngModel)]="myVal"` + this.bsStr;
    this.customCompCode += `(ngModelChange)="doSomething($event)"`;

    if (this.compConf.hasLabel)   { this.customCompCode += this.bsStr + `bfLabel="${this.compConf.labelText}"`; }
    if (this.compConf.isRequired) { this.customCompCode += this.bsStr + `[bfRequired]="true"`; }
    if (this.compConf.isDisabled) { this.customCompCode += this.bsStr + `[bfDisabled]="true"`; }

    if (this.compConf.hasTooltip) {
      this.customCompCode += this.bsStr + `bfTooltip="${this.compConf.tooltipText}"`;
      if (!!this.compConf.tooltipPos)  { this.customCompCode += this.bsStr + `bfTooltipPos="${this.compConf.tooltipPos}"`; }
      if (!!this.compConf.tooltipBody) { this.customCompCode += this.bsStr + `bfTooltipBody="${this.compConf.tooltipBody}"`; }
    }

    this.customCompCode += (`>` + this.brStr + `</bf-textarea>`);
  }





  constructor() { }

  ngOnInit() { }

}


export const BfPrototypesDoc = {
  name    : `bfPrototypes`,
  uiType  : 'function',
  desc    : `Collection of helper functions to perform basic variable types operations`,
  api     : `[bfText]: Button text`,
  instance: `<bf-prototypes></bf-prototypes>`,
  demoComp: BfPrototypesDemoComponent
};
