// bf-range-slider = 'bf-btn'
// BfRangeSlider = 'BfBtn'


import { Component, OnInit } from '@angular/core';
import {LabelType} from 'ng5-slider';

@Component({
  selector: 'app-bf-range-slider-demo',
  templateUrl: './bf-range-slider-demo.component.html',
  styleUrls: ['./bf-range-slider-demo.component.scss']
})
export class BfRangeSliderDemoComponent implements OnInit {
  public name = BfRangeSliderDoc.name;
  public desc = BfRangeSliderDoc.desc;
  public api = BfRangeSliderDoc.api;
  public instance = BfRangeSliderDoc.instance;

//   public instance2 =
// `<bf-range-slider</bf-range-slider>`;


  public cssReset = `$slider_bg            : $white !default;
$slider_color_default : $light !default;
$slider_color_disabled: $disabled-color !default;
$slider_color_primary : $primary_color !default;`;

  public slider1 = { min: 40, max: 60 };
  public slider1Options: any = { start: 0, end: 100, step: 5, showTicks: true, showTicksValues: true, tickStep: 10, tickValueStep: 20, maxLimit: 85, minLimit: 15 };
  public instance1Obj = `valueOptions = {
  start: 0,
  end: 100,
  step: 5,
  showTicks: true,
  showTicksValues: true,
  tickStep: 10,
  tickValueStep: 20,
  maxLimit: 85,
  minLimit: 15
}`;

  public slider2 = { min: 40, max: 60};
  public slider2Options: any = { start: 0, end: 100, showTicks: true, tickStep: 10, maxRange: 60, minRange: 20 };
  public instance2Obj = `valueOptions = {
  start: 0,
  end: 100,
  showTicks: true,
  tickStep: 10,
  maxRange: 60,
  minRange: 20
}`;
  public instance2 = `<bf-range-slider [(ngModel)]="slider2"
                 [bfOptions]="slider2Options">
</bf-range-slider>`;

  public slider3 = { min: 40, max: 150};
  public slider3Options: any = { start: 0, end: 300, tickArray: [0, 60, 120, 180, 240, 300], showTicks: true, showTicksValues: true };
  public instance3Obj = `customLabel(val: number, type: LabelType) {
  switch (label) {
    case LabelType.Low:
      return 'from: ' + value;
    case LabelType.High:
      return 'to: ' + value;
    default:
      return value;
  }
}`;
  public instance3 = `<bf-range-slider [(ngModel)]="slider3"
                 [bfOptions]="slider3Options"
                 [bfCustomSliderLabel]="customLabel">
</bf-range-slider>`;




  public valueSlider = { min: 30, max: 100 };
  public sliderOptions: any = { start: 0, end: 150, showTicks: true, showTicksValues: true, tickStep: 25 };

  public sliderModelCode = `myVal = {
  min: ${this.valueSlider.min},
  max: ${this.valueSlider.max}
}`;
  public sliderOptionsCode = `sliderOptions = {
  start: 0,
  end: 150,
  showTicks: true,
  showTicksValues: true,
  tickStep: 25
}`;

  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n                 `;
  public customCompCode = `<bf-range-slider [(ngModel)]="selObj" [bfList]="myList"></bf-range-slider>`;
  public compConf: any = {
    isRequired: false,
    isDisabled: false,
    rows: null,
    showOuterSection: false,
    hasLabel: false,   labelText: 'My Description',
    hasTooltip: false, tooltipText: 'Hello World', tooltipPos: null
  };
  public upComp = () => {
    this.customCompCode = `<bf-range-slider `;

    /*let compClasses = '';
    if (this.compConf.hasFullWidth) { compClasses += (!!compClasses.length ? ' ' : '') + 'full-width'; }
    if (this.compConf.hasSquash)    { compClasses += (!!compClasses.length ? ' ' : '') + 'squash'; }
    if (!!compClasses) {
      this.customCompCode += `class="${compClasses}"` + this.bsStr;
    }*/
    this.customCompCode += `[(ngModel)]="myVal"`;
    this.customCompCode += this.bsStr + `[bfOptions]="sliderOptions"`;

    // if (this.compConf.isRequired) { this.customCompCode += this.bsStr + `[bfRequired]="true"`; }
    if (this.compConf.showOuterSection) { this.customCompCode += this.bsStr + `[bfShowOuterSection]="true"`; }
    if (this.compConf.isDisabled) { this.customCompCode += this.bsStr + `[bfDisabled]="true"`; }

    if (this.compConf.hasLabel)   { this.customCompCode += this.bsStr + `bfLabel="${this.compConf.labelText}"`; }

    if (this.compConf.hasTooltip) {
      this.customCompCode += this.bsStr + `bfTooltip="${this.compConf.tooltipText}"`;
      if (!!this.compConf.tooltipPos)  { this.customCompCode += this.bsStr + `bfTooltipPos="${this.compConf.tooltipPos}"`; }
    }

    this.customCompCode += (`>` + this.brStr + `</bf-range-slider>`);
  };

  public upSliders = () => {
    this.sliderModelCode = `ngModel.min = ${this.valueSlider.min}
ngModel.max = ${this.valueSlider.max}`;
    this.sliderOptionsCode = `sliderOptions = {
  start: 0,
  end: 150,
  showTicks: true,
  showTicksValues: true,
  tickStep: 25
}`;
  };

  newTranslate = (value: number, label: LabelType) => {
    const min = Math.trunc(value / 60);
    const sec = value % 60;
    switch (label) {
      case LabelType.Low:
        return `from: 0${min}:${sec > 10 ? sec : '0' + sec}`;
      case LabelType.High:
        return `to: 0${min}:${sec > 10 ? sec : '0' + sec}`;
      default:
        return `0${min}:${sec > 10 ? sec : '0' + sec}`;
    }
  };




  constructor() { }

  ngOnInit() { }

}


export const BfRangeSliderDoc = {
  name    : `bf-range-slider`,
  uiType  : 'component',
  desc    : `Generates a range slider component`,
  api     : `[(ngModel)]         :The ngModel is linked as an Object on the Range Slider:
                        {
                          min: (Number) - low value of the range,
                          max: (Number) - high value of the range
                        }
[bfOptions]          : The Config options for the Slider:
                       {
                         start        : Initial range
                         end          : Final range
                         step         : (Optional) Step between each value
                         showSelectionBar: (Optional) Set to true to show the selection bar before the slider handle
                         showSelectionBarEnd: (Optional) Set to true to show the selection bar after the slider handle
                         showTicks    : (Optional) Set to true to display a tick for each step on the slider
                         showTicksValues: (Optional) Set true to display the value for each tick
                         tickStep     : (Optional) Number - Set the steps to be ticked
                         tickArray    : (Optional) Array - Set specific steps to be ticked
                         tickValueStep: (Optional) Number - Set the steps to show the value
                         maxLimit     : (Optional) Number - max value authorized on the slider
                         minLimit     : (Optional) Number - min value authorized on the slider
                         maxRange     : (Optional) Number - maximum range authorized on the slider
                         minRange     : (Optional) Number - minimum range authorized on the slider
                       }
[bfCustomSliderLabel]: [method] = (value: number, label LabelType: LabelType): string => return (The label to be shown as a label on the range)
[bfDisabled]         : Whether the slider is disabled or not
[bfShowOuterSection] : Set to true to change the bar color to left/right bars
[bfLabel]            : Label of the input (automatically translated). If not provided, no label is displayed.
[bfLabelTooltips]    : If label provided, adds a info badge with a tooltip (automatically translated)
[bfLabelTooltipPos]  : Position of the tooltip (top by default)

(bfMinOnChange)      : Trigger when min value has been changed
(bfMaxOnChange)      : Trigger when max value has been changed`,
  instance: `<bf-range-slider [(ngModel)]="value"
                 bfLabel="Test 1"
                 [bfOptions]="valueOptions">
</bf-range-slider>`,
  demoComp: BfRangeSliderDemoComponent
};
