// bf-slider = 'bf-btn'
// BfSlider = 'BfBtn'


import { Component, OnInit } from '@angular/core';
import {LabelType} from 'ng5-slider';

@Component({
  selector: 'app-bf-slider-demo',
  templateUrl: './bf-slider-demo.component.html',
  styleUrls: ['./bf-slider-demo.component.scss']
})
export class BfSliderDemoComponent implements OnInit {
  public name = BfSliderDoc.name;
  public desc = BfSliderDoc.desc;
  public api = BfSliderDoc.api;
  public instance = BfSliderDoc.instance;



  public cssReset = `$optional_input_color : $optional-color;
$focused_input_color  : $focused-color;
$required_input_color : $primary_color;
$invalid_input_color  : $invalid-color;
$valid_input_color    : $primary_color;
$disabled_input_color : $disabled-color;

.bf-slider-form-group {
  ...
}`;

  public slider1 = 50;
  public slider1Options = { start: 10, end: 20, step: 2, showTicks: true, showTicksValues: true };
  public instance1Obj = `valueOptions = {
  start: 10, 
  end: 20, 
  step: 2, 
  showTicks: true,
  showTicksValues: true
}`;

  public slider2;
  public slider2High = 70;
  public slider2Options = { start: 20, end: 120, showTicks: true, showTicksValues: true, tickStep: 10, tickValueStep: 20 };
  public instance2Obj = `valueOptions = { 
  start: 10, 
  end: 150, 
  showTicks: true
  showTicksValues: true, 
  tickStep: 5, 
  tickValueStep: 10 
}`;
  public instance2 = `<bf-slider [(ngModel)]="value"
           [(bfHighValue)]="valueHigh"
           [bfOptions]="valueOptions">
</bf-slider>`;

  public slider3 = 15;
  public slider3Options = { start: 0, end: 100, showTicks: true, tickArray: [5, 10, 15, 25, 40, 65, 100], showTicksValues: true };
  public instance3Obj = `valueOptions = { 
  start: 10, 
  end: 100, 
  showTicks: true
  tickArray: [5,10,15,25,40,65,100],
  showTicksValues: true 
}`;
  public instance3 = `<bf-slider [(ngModel)]="value"
           [bfOptions]="valueOptions">
</bf-slider>`;

  public slider4 = 15;
  public slider4Options = {start: 0, end: 100};
  public instance4Obj = `translateFunc = (value: number)=>{
  return value + ' $';
}`;
  public instance4 = `<bf-slider [(ngModel)]="value"
           [bfOptions]="valueOptions"
           [bfTranslate]="translateFunc">
</bf-slider>`;

  public slider5 = 80;
  public slider5High = 180;
  public slider5Options = { start: 60, end: 300, showTicks: true, tickArray: [60, 120, 180, 240, 300], showTicksValues: true };
  public instance5Obj = `translateFunc(value: number, label: LabelType) {
  switch (label) {
    case LabelType.Low:
      return 'From:'+value;
    case LabelType.High:
      return 'To:'+value;
    default:
      return value;
  }
}`;
  public instance5 = `<bf-slider [(ngModel)]="value"
           [(bfHighValue)]="valueHigh"
           [bfOptions]="valueOptions"
           [bfTranslate]="translateFunc">
</bf-slider>`;


  public valueSlider = 50;
  public valueSliderHigh = 100;
  public sliderOptions: any = {
    start: 0,
    end: 150
  };


  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n           `;
  public customCompCode = `<bf-slider [(ngModel)]="selObj" [bfList]="myList"></bf-slider>`;
  public compConf: any = {
    addSecondValue: false,
    showOuterSection: false,
    isRequired: false,
    isDisabled: false,
    rows: null,
    hasLabel: false,   labelText: 'My Description',
    hasTooltip: false, tooltipText: 'Hello World', tooltipPos: null
  };

  public upComp = () => {
    this.customCompCode = `<bf-slider `;

    this.customCompCode += `[(ngModel)]="myVal"`;
    if (this.compConf.addSecondValue) { this.customCompCode += this.bsStr + `[(bfHighValue)]="mySecondVal"`; }

    this.customCompCode += this.bsStr + `[bfOptions]="sliderOptions"`;

    if (this.compConf.showOuterSection) { this.customCompCode += this.bsStr + `[bfShowOuterSection]="true"`; }
    if (this.compConf.isRequired) { this.customCompCode += this.bsStr + `[bfRequired]="true"`; }
    if (this.compConf.isDisabled) { this.customCompCode += this.bsStr + `[bfDisabled]="true"`; }

    if (this.compConf.hasLabel)   { this.customCompCode += this.bsStr + `bfLabel="${this.compConf.labelText}"`; }

    if (this.compConf.hasTooltip) {
      this.customCompCode += this.bsStr + `bfTooltip="${this.compConf.tooltipText}"`;
      if (!!this.compConf.tooltipPos)  { this.customCompCode += this.bsStr + `bfTooltipPos="${this.compConf.tooltipPos}"`; }
    }

    this.customCompCode += (`>` + this.brStr + `</bf-slider>`);

  };

  public newTranslate = (value: number): string => `${value} $`;

  public translate2 = (value: number, label: LabelType) => {
    const labelValue = `${Math.trunc(value / 60)}:${value % 60 > 10 ? value % 60 : '0' + value % 60}`;
    switch (label) {
      case LabelType.Low:
        return `From: ${labelValue}`;
      case LabelType.High:
        return `To: ${labelValue}`;
      default:
        return labelValue;
    }
  };



  constructor() { }

  ngOnInit() { }

}


export const BfSliderDoc = {
  name    : `bf-slider`,
  uiType  : 'component',
  desc    : `Generates a slider component`,
  api     : `[(ngModel)]    : The ngModel directive is linked as value on the Slider
[bfHighValue]  : Second value which will display a Range
[bfOptions]    : The Config options for the Slider: 
                 {
                  start     : Initial range
                  end       : Final range
                  step      : (Optional) Step between each value
                  showTicks : (Optional) Set to true to display a tick for each step on the slider
                 }
[bfDisabled]   : Whether the slider is disabled or not
             
[bfLabel]      : Label of the input (automatically translated). If not provided, no label is displayed.
[bfLabelPos]   : Position of the label (top | left). By default = top.
[bfTooltips]   : If label provided, adds a info badge with a tooltip (automatically translated)
[bfTooltipPos] : Position of the tooltip (top by default)
[bfRequired]   : Whether the value is required. If not, and "Empty" option will be added a the top of the list`,
  instance: `<bf-slider [(ngModel)]="value" 
           bfLabel="Test 1" 
           [bfOptions]="valueOptions">
</bf-slider>`,
  demoComp: BfSliderDemoComponent
};
