// bf-date-picker = 'bf-btn'
// BfDatePicker = 'BfBtn'


import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-bf-date-picker-demo]',
  templateUrl: './bf-date-picker-demo.component.html',
  styleUrls: ['./bf-date-picker-demo.component.scss']
})
export class BfDatePickerDemoComponent implements OnInit {
  public name = BfDatePickerDoc.name;
  public desc = BfDatePickerDoc.desc;
  public api = BfDatePickerDoc.api;
  public instance = BfDatePickerDoc.instance;

  public instance2 = `<bf-date-picker</bf-date-picker>`;

  public cssReset = `$optional_input_color : $optional-color;
$focused_input_color  : $focused-color;
$required_input_color : $primary_color;
$invalid_input_color  : $invalid-color;
$valid_input_color    : $primary_color;
$disabled_input_color : $disabled-color;

.bf-date-picker-form-group {
  ...
}`;

  // ---- This is the logic to manage autogenerated code example ----
  public brStr = `\n`;
  public bsStr = `\n             `;
  public customCompCode = null;
  public compConf: any = {
    data: {
      ngModel : new Date('Thu Oct 31 2019 00:00:00 GMT+0000 (Greenwich Mean Time)'),
      ngInputModel: null,
      min: null,
      inputMin: null,
      max: null,
      inputMax: null
    },
    isRequired: false,
    hasLabel: false, labelText: 'My Description',
    // hasTooltip: false, tooltipText: 'Hello World', tooltipPos: null, tooltipBody: false,
    convertToText(value) {
      this.data.ngInputModel = !!value ? value.toString() : null;
    },
    convertToDate() {
      const converter = (input) => {
        return !!input && new Date(input).toString() !== 'Invalid Date' ? new Date(input) : null;
      };
      this.data.ngModel = converter(this.data.ngInputModel);
      this.data.min = converter(this.data.inputMin);
      this.data.max = converter(this.data.inputMax);
    }
  };
  public upComp = () => {
    this.customCompCode = `<bf-date-picker `;
    this.customCompCode += `[(ngModel)]="myVal"` + this.bsStr;
    this.customCompCode += `(ngModelChange)="doSomething($event)"`;

    if (this.compConf.hasLabel)   { this.customCompCode += this.bsStr + `bfLabel="${this.compConf.labelText}"`; }
    if (this.compConf.isRequired) { this.customCompCode += this.bsStr + `[bfRequired]="true"`; }

    // if (this.compConf.hasTooltip) {
    //   this.customCompCode += this.bsStr + `bfTooltip="${this.compConf.tooltipText}"`;
    //   if (!!this.compConf.tooltipPos)  { this.customCompCode += this.bsStr + `bfTooltipPos="${this.compConf.tooltipPos}"`; }
    //   if (!!this.compConf.tooltipBody) { this.customCompCode += this.bsStr + `bfTooltipBody="${this.compConf.tooltipBody}"`; }
    // }

    this.customCompCode += (`>` + this.brStr + `</bf-date-picker>`);
  };





  constructor() { }

  ngOnInit() { }

}


export const BfDatePickerDoc = {
  name    : `bf-date-picker`,
  uiType  : 'component',
  desc    : `Generates a ....`,
  api     : `[bfText]: The text... `,
  instance: `<bf-date-picker></bf-date-picker>`,
  demoComp: BfDatePickerDemoComponent
};
